# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  
  desc "Builds the Android App Bundle for the Play Store"
  lane :playstore do
    gradle(
      task: 'bundleRelease'
    )
    
    upload_to_play_store(
      json_key: 'fastlane/mitalicredential.json',
      track: 'internal',
      release_status: 'draft'
    )
  end
  
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      task: 'clean assembleRelease'
    )
    
    upload_to_play_store(
      json_key: 'fastlane/mitalicredential.json'
    )
  end
end
